### ISSUE TITLE
Fatal error on creating consignment for pickup point

### ISSUE THREAD

**Issue by alexroosenstein** [myparcelnl/sdk#313]
When creating a consignment and supplying it with an address of a pickup point the following fatal error occurs.
For reproduction purposes, the address apparently belongs to "De Kade Post".
I am using an older version of this library, but the relevant code seems identical to the current version.

```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to MyParcelNL\Sdk\src\Model\Consignment\AbstractConsignment::setPickupNumber() must be of the type string, integer given, called in /myparcelnl/sdk/src/Adapter/ConsignmentAdapter.php on line 214 and defined in myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php:1640
Stack trace:
#0 myparcelnl/sdk/src/Adapter/ConsignmentAdapter.php(214): MyParcelNL\Sdk\src\Model\Consignment\AbstractConsignment-&gt;setPickupNumber(111)
#1 myparcelnl/sdk/src/Adapter/ConsignmentAdapter.php(184): MyParcelNL\Sdk\src\Adapter\ConsignmentAdapter-&gt;setByMethods(Array, Array)
#2 myparcelnl/sdk/src/Adapter/ConsignmentAdapter.php(44): MyParcelNL\Sdk\src\Adapter\ConsignmentAdapter-&gt;pickup()
#3 myparcelnl in <b>myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php</b> on line <b>1640</b><br />
```

**Comment by Mitchell-MyParcel** [comment]
@alexroosenstein Just to be sure; you are having this issue when an address is entered which unbeknownst is to you a pickup address but not a pickup address that is specifically selected as such in our checkout delivery options? If this is indeed the case than we can reproduce this issue and will work on solving it.

**Comment by svenvanhees** [comment]
Can confirm. I get the same issue for a client of mine. A customer of my client entered an pickup point unbeknownst to us. Which results in the error as supplied by @alexroosenstein.

**Comment by Mitchell-MyParcel** [comment]
@svenvanhees: Thanks for the confirmation. We are on it.

**Comment by peterquentin** [comment]
@Mitchell-MyParcel Any updates on this? I received the same error.

My only option right now is to create the shipment manually in postnl backend right?

**Comment by iamniels** [comment]
Could this issue receive some attention? It's a PITA in our workflow. 

Regardless of the exception, the label is being created, so I'm unable handle the exception properly.

**Comment by iamniels** [comment]
I'm now using this SDK which has much less issues and is much more modern: https://github.com/ecommercegeeks/myparcelnl-sdk

**Comment by FreekVR** [comment]
Our upcoming v11 release (now in beta) will replace Consigments with APIs directly based on an OpenAPI specification of our API. I am closing this issue because this problem does not apply to that upcoming version.
